const icons = [
    {
        key:1,
        url:"./images/icons/java.gif",
        title:"Java"
    },
    {
        key:2,
        url:"./images/icons/c++.png",
        title:"C++"
    },
    {
        key:3,
        url:"./images/icons/javascript.gif",
        title:"Javascript"
    },
    {
        key:4,
        url:"./images/icons/html.gif",
        title:"HTML"
    },
    {
        key:5,
        url:"./images/icons/css.png",
        title:"CSS"
    },
    {
        key:6,
        url:"./images/icons/react.gif",
        title:"React Js"
    },
    {
        key:7,
        url:"./images/icons/nodejs.png",
        title:"Nodejs"
    },
    {
        key:8,
        url:"./images/icons/bootstrap.png",
        title:"Bootstrap"
    },
    {
        key:9,
        url:"./images/icons/json.png",
        title:"Json"
    }
]

export default icons;